#!/bin/bash

# Randomly iterate through a subset of machines in UG04
# You must be in a School machine (such as tinky-winky), or
# or have a School active vpn connection.

while true; do
        suffix=$((10 + RANDOM % 50))
        machine="cca-ug04-130${suffix}.cs.bham.ac.uk"
        echo "Trying $machine"
        ping=`ping -c 1 -t 1 $machine | grep bytes | wc -l`
	if [ "${ping}" -gt 0 ];then
	    ssh -o StrictHostKeyChecking=no $machine
            break
	fi
done
