#!/bin/bash

# Script to connect to a school computer. Presumably by George Brighton.

# will hold available machine hostnames
alive=()

# iterate through a subset of machines in UG04
for suffix in {30..100}; do

	# ping each one
	ping -c 1 -t 1 "cca-ug04-130$suffix" > /dev/null 2>&1
	
	# if the ping command succeeded, the machine is available
	if [ $? -eq 0 ]; then
		
		# add it to the list
		alive+=("cca-ug04-130$suffix")
	fi
done

# count the number of available machines
count=${#alive[@]}
echo "Found $count machines."

# pick a machine from the list at random
theChosenOne=${alive[$((RANDOM % $count))]}

# connect to it, accepting any unseen host key
echo "Connecting to $theChosenOne..."
ssh -o StrictHostKeyChecking=no "$theChosenOne"
