#!/usr/bin/env python2

import uu, sys, os, os.path



of = open('../uudecode/input', 'wb')
of.write(sys.stdin.read()) # already in binary mode, hopefully
of.close()

iff = open('../uudecode/input', 'r')
firstline = iff.readline()
_, _, filename = firstline.split(' ', 2)
if os.path.exists(filename.rstrip()):
	os.unlink(filename.rstrip())

uu.decode('../uudecode/input')
